# IMDB Dataset - Create Weak Supervision Sources

This notebook shows how to create labeling functions on the IMDB Movie Review dataset.

This dataset has gold labels. These labels are just there for evaluation purposes. The idea of using weak supervision and especially knodle is that you don't have a dataset which is purely labeled with strong supervision (manual) and instead label it with weak supervision.

First, we load the dataset from kaggle. Then, we will look at certain keywords within both sentiments and find good matching keywords which will act as a weak supervision source. Finally, the keywords on a basic majority vote model.

## Imports

Lets make some basic imports 

In [1]:
import pandas as pd 
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS, CountVectorizer
from bs4 import BeautifulSoup
from snorkel.labeling import LabelingFunction, PandasLFApplier, filter_unlabeled_dataframe, LFAnalysis
from snorkel.labeling.model import MajorityLabelVoter, LabelModel
import numpy as np 
from tqdm import tqdm

In [2]:
# Init
tqdm.pandas()
pd.set_option('display.max_colwidth', -1)

/Users/sandro/.pyenv/versions/3.7.1/envs/imdbTut/lib/python3.7/site-packages/tqdm/std.py:703: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel
/Users/sandro/.pyenv/versions/3.7.1/envs/imdbTut/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  This is separate from the ipykernel package so we can avoid doing imports until


In [3]:
# Constants
POSITIVE = 1
NEGATIVE = 0
ABSTAIN = -1
COLUMN_WITH_TEXT = "reviews_preprocessed"

## Download the raw dataset

Now we download the dataset we need. For that you need to have the kaggle-cli installed and configured with your API key. Please have a look at the official [documentation](https://github.com/Kaggle/kaggle-api) for further instructions.

In [4]:
!kaggle datasets download -d lakshmi25npathi/imdb-dataset-of-50k-movie-reviews
!tar -xvf imdb-dataset-of-50k-movie-reviews.zip
!rm imdb-dataset-of-50k-movie-reviews.zip

/Users/sandro/.pyenv/versions/3.7.1/envs/imdbTut/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.0) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
 93%|███████████████████████████████████▍  | 24.0M/25.7M [00:01<00:00, 24.2MB/s]
100%|██████████████████████████████████████| 25.7M/25.7M [00:01<00:00, 24.6MB/s]
x IMDB Dataset.csv


## Preview dataset

After downloading and unpacking the dataset we can have a first look at it and work with it.

In [5]:
imdb_dataset_raw = pd.read_csv('IMDB Dataset.csv')

In [6]:
imdb_dataset_raw.head()

review  \
0  One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.   
1  A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master's of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional 'dream' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell's murals decorating every surface) are terribly well done.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
2  I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). While some may be disappointed when they realize this is not Match Point 2: Risk Addiction, I thought it was proof that Woody Allen is still fully in control of the styl

In [7]:
imdb_dataset_raw.groupby('sentiment').count()


review
sentiment        
negative   25000 
positive   25000

In [8]:
imdb_dataset_raw.isna().sum()

review       0
sentiment    0
dtype: int64

## Preprocess dataset

Now lets take some basic preprocessing steps

### Remove Stopwords

We begin by removing all common stop words. We use `scikit-learn`'s stopwords that we don't install to many packages.

In [9]:
imdb_dataset_raw['reviews_preprocessed'] = imdb_dataset_raw['review'].apply(
    lambda x: ' '.join([word for word in x.split() if word not in (ENGLISH_STOP_WORDS)]))

In [10]:
imdb_dataset_raw.head()

review  \
0  One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.   
1  A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master's of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional 'dream' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell's murals decorating every surface) are terribly well done.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
2  I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). While some may be disappointed when they realize this is not Match Point 2: Risk Addiction, I thought it was proof that Woody Allen is still fully in control of the styl

### Remove HTML Tags

The dataset contains many HTML tags. We'll remove them

In [11]:
def strip_html(text):
    soup = BeautifulSoup(text, "html.parser")
    return soup.get_text()

imdb_dataset_raw['reviews_preprocessed'] = imdb_dataset_raw['reviews_preprocessed'].apply(
    lambda x: strip_html(x))

In [12]:
imdb_dataset_raw['reviews_preprocessed'].head()

0    One reviewers mentioned watching just 1 Oz episode you'll hooked. They right, exactly happened me.The thing struck Oz brutality unflinching scenes violence, set right word GO. Trust me, faint hearted timid. This pulls punches regards drugs, sex violence. Its hardcore, classic use word.It called OZ nickname given Oswald Maximum Security State Penitentary. It focuses mainly Emerald City, experimental section prison cells glass fronts face inwards, privacy high agenda. Em City home many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish more....so scuffles, death stares, dodgy dealings shady agreements far away.I say main appeal fact goes shows wouldn't dare. Forget pretty pictures painted mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The episode I saw struck nasty surreal, I couldn't say I ready it, I watched more, I developed taste Oz, got accustomed high levels graphic violence. Not just violence, injustice (crooked guards who'll sold n

## Count Words

Now we want to count the words per sentiment to find good matching keywords.
We split the dataset first into positive and negative reviews and then count the words per sentiment

In [13]:
positive_reviews = \
    imdb_dataset_raw.loc[imdb_dataset_raw.sentiment == 'positive', ['reviews_preprocessed', 'sentiment']]

In [14]:
negative_reviews = \
    imdb_dataset_raw.loc[imdb_dataset_raw.sentiment == 'negative', ['reviews_preprocessed', 'sentiment']]

In [15]:
def get_word_count_list(reviews: pd.DataFrame, min_df: int = 10) -> pd.DataFrame:
    vectorizer = CountVectorizer(min_df=min_df)
    X = vectorizer.fit_transform(reviews.reviews_preprocessed.values)
    word_list = vectorizer.get_feature_names()
    count_list = X.toarray().sum(axis=0)
    word_count = pd.DataFrame(dict(zip(word_list, count_list)), index=['count']).transpose().sort_values('count', ascending=False)
    # Remove stop words again
    word_count = word_count.loc[~word_count.index.isin(ENGLISH_STOP_WORDS)]
    return word_count

### Positive Reviews

First lets look at some positive reviews and find good keywords which maybe describe them.

In [16]:
word_count_positive = get_word_count_list(positive_reviews, min_df=100)

In [17]:
word_count_positive.describe()

count
count  3627.000000 
mean   557.271574  
std    1355.342072 
min    100.000000  
25%    159.000000  
50%    253.000000  
75%    507.000000  
max    42093.000000

In [18]:
# All words in quantile 95 and higher
q95_positive_words =  word_count_positive.loc[word_count_positive['count'] > word_count_positive.quantile(0.95)['count']]

In [19]:
q95_positive_words.index.values

array(['film', 'movie', 'like', 'good', 'just', 'great', 'story', 'time',
       'really', 'people', 'love', 'best', 'life', 'way', 'films',
       'think', 'characters', 'don', 'movies', 'character', 'seen', 'man',
       'watch', 'make', 'little', 'does', 'know', 'did', 'years', 'end',
       'scene', 'real', 'scenes', 'say', 'acting', 'plot', 'world',
       'makes', 'better', 'new', 've', '10', 'young', 'work', 'old',
       'lot', 'quite', 'cast', 'funny', 'series', 'director', 'actors',
       'music', 'role', 'watching', 'look', 'bad', 'doesn', 'family',
       'performance', 'things', 'comedy', 'times', 'going', 'big', 'saw',
       'long', 'thing', 'actually', 'excellent', 'didn', 'bit', 'fun',
       'right', 'action', 'thought', 'fact', 'feel', 'want', 'come',
       'played', 'especially', 'got', 'war', 'horror', 'beautiful', 'day',
       'pretty', 'dvd', 'different', 'shows', 'gets', 'tv', 'interesting',
       'true', 'job', 'll', 'woman', 'probably', 'far', 'wonderful',

In [20]:
# Manual create list with keywords
positive_keywords = [
    'like','good','great','love', 'best', 'funny','excellent','fun','beautiful','interesting','wonderful',
    'original','perfect','classic','loved','recommend','amazing','favorite'
]

In [21]:
imdb_dataset_raw.loc[imdb_dataset_raw.reviews_preprocessed.str.contains('like')]

review  \
3      Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
5      Probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it's not preachy or boring. It just never gets old, despite my having seen it some 15 or more times in the last 25 years. Paul Lukas' performance brings tears to my eyes, and Bette Davis, in one of her very few truly sympathetic roles, is a delight. The kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. And the mother's slow awakening to what's happening in the world and under her own roof is believable and startling. If I had a dozen thumbs, they'd all be "up" for this movie.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       

### Negative Reviews

Lets do the same process with negative reviews and find some keywords which describe bad movie reviews.

In [22]:
word_count_negative = get_word_count_list(negative_reviews, min_df=100)

In [23]:
word_count_negative.describe()

count
count  3356.000000 
mean   593.115018  
std    1543.380762 
min    100.000000  
25%    160.000000  
50%    252.000000  
75%    525.000000  
max    50090.000000

In [24]:
# All words in quantile 95 and higher
q95_negative_words = word_count_negative.loc[
    word_count_negative['count'] > word_count_negative.quantile(0.95)['count']]

In [25]:
q95_negative_words.index.values

array(['movie', 'film', 'like', 'just', 'good', 'bad', 'time', 'really',
       'don', 'story', 'people', 'make', 'movies', 'plot', 'acting',
       'way', 'characters', 'watch', 'think', 'did', 'character', 'know',
       'better', 'seen', 'films', 'little', 'say', 'scene', 'thing',
       'end', 'does', 'scenes', 've', 'didn', 'watching', 'great',
       'doesn', 'actually', 'man', 'actors', 'worst', 'director', 'life',
       'funny', 'going', 'look', 'love', 'real', 'minutes', 'old',
       'pretty', 'horror', 'want', 'best', 'script', 'guy', 'work', '10',
       'got', 'lot', 'isn', 'things', 'original', 'fact', 'thought',
       'makes', 'point', 'new', 'big', 'long', 'years', 'gets', 'far',
       'interesting', 'cast', 'making', 'right', 'action', 'come',
       'awful', 'quite', 'money', 'll', 'kind', 'poor', 'comedy',
       'boring', 'trying', 'reason', 'stupid', 'probably', 'looking',
       'looks', 'instead', 'terrible', 'away', 'maybe', 'believe', 'saw',
       'girl', '

In [26]:
negative_keywords = [
    'bad', 'worst','horror','awful','poor','boring','stupid','terrible','waste','worse','horrible'
]

## Labeling Functions

Now we start to build labeling functions with Snorkel with these keywords and check the coverage.

This is an iterative process of course so we surely have to add more keywords and regulary expressions ;-) 

In [27]:
def keyword_lookup(x, keyword, label):
    return label if keyword in x[COLUMN_WITH_TEXT].lower() else ABSTAIN


In [28]:
def make_keyword_lf(keyword: str, label: str) -> LabelingFunction:
    """
    Creates labeling function based on keyword.
    Args:
        keywords:
        label:

    Returns:

    """
    return LabelingFunction(
        name=f"keyword_{keyword}",
        f=keyword_lookup,
        resources=dict(keyword=keyword, label=label),
    )

In [29]:
def create_labeling_functions(keywords: pd.DataFrame) -> np.ndarray:
    """
    Create Labeling Functions based on the columns keyword and regex. Appends column lf to df.

    Args:
        keywords: DataFrame with processed keywords

    Returns:
        All labeling functions. 1d Array with shape: (number_of_lfs x 1)
    """
    keywords = keywords.assign(lf=keywords.progress_apply(
        lambda x:make_keyword_lf(x.keyword, x.label_id), axis=1
    ))
    lfs = keywords.lf.values
    return lfs

In [30]:
def make_keyword_df(positive_keywords: [str], negative_keywords: [str]) -> pd.DataFrame:
    positive = pd.DataFrame(
        pd.Series({x: 'positive' for (x) in positive_keywords}, name="label")).reset_index().rename(columns={"index":"keyword"})
    
    negative = pd.DataFrame(
        pd.Series({x: 'negative' for (x) in negative_keywords}, name="label")).reset_index().rename(columns={"index":"keyword"})
    keywords = positive.append(negative)
    
    assert len(positive) + len(negative) == len(keywords), "Shapes doesn't match"
    
    keywords.loc[keywords.label == 'positive', 'label_id'] = int(POSITIVE)
    keywords.loc[keywords.label == 'negative', 'label_id'] = int(NEGATIVE)
    keywords.reset_index(inplace=True, drop=True)
    return keywords


In [31]:
keywords = make_keyword_df(positive_keywords, negative_keywords)

In [32]:
keywords

keyword     label  label_id
0   like         positive  1.0     
1   good         positive  1.0     
2   great        positive  1.0     
3   love         positive  1.0     
4   best         positive  1.0     
5   funny        positive  1.0     
6   excellent    positive  1.0     
7   fun          positive  1.0     
8   beautiful    positive  1.0     
9   interesting  positive  1.0     
10  wonderful    positive  1.0     
11  original     positive  1.0     
12  perfect      positive  1.0     
13  classic      positive  1.0     
14  loved        positive  1.0     
15  recommend    positive  1.0     
16  amazing      positive  1.0     
17  favorite     positive  1.0     
18  bad          negative  0.0     
19  worst        negative  0.0     
20  horror       negative  0.0     
21  awful        negative  0.0     
22  poor         negative  0.0     
23  boring       negative  0.0     
24  stupid       negative  0.0     
25  terrible     negative  0.0     
26  waste        negative  0.0     
27  worse        negative  0.0     
28  horrible     negative  0.0

In [33]:
labeling_functions = create_labeling_functions(keywords)

100%|██████████| 29/29 [00:00<00:00, 7631.75it/s]


In [34]:
labeling_functions

array([LabelingFunction keyword_like, Preprocessors: [],
       LabelingFunction keyword_good, Preprocessors: [],
       LabelingFunction keyword_great, Preprocessors: [],
       LabelingFunction keyword_love, Preprocessors: [],
       LabelingFunction keyword_best, Preprocessors: [],
       LabelingFunction keyword_funny, Preprocessors: [],
       LabelingFunction keyword_excellent, Preprocessors: [],
       LabelingFunction keyword_fun, Preprocessors: [],
       LabelingFunction keyword_beautiful, Preprocessors: [],
       LabelingFunction keyword_interesting, Preprocessors: [],
       LabelingFunction keyword_wonderful, Preprocessors: [],
       LabelingFunction keyword_original, Preprocessors: [],
       LabelingFunction keyword_perfect, Preprocessors: [],
       LabelingFunction keyword_classic, Preprocessors: [],
       LabelingFunction keyword_loved, Preprocessors: [],
       LabelingFunction keyword_recommend, Preprocessors: [],
       LabelingFunction keyword_amazing, Preproce

### Apply Labeling Functions

Now lets apply all labeling functions on our reviews and check some statistics.

In [105]:
applier = PandasLFApplier(lfs=labeling_functions)
applied_lfs = applier.apply(df=imdb_dataset_raw)

/Users/sandro/.pyenv/versions/3.7.1/envs/imdbTut/lib/python3.7/site-packages/tqdm/std.py:703: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel
100%|██████████| 50000/50000 [00:09<00:00, 5269.64it/s]


In [36]:
applied_lfs

array([[-1, -1, -1, ..., -1, -1, -1],
       [-1, -1,  1, ..., -1, -1, -1],
       [-1, -1,  1, ..., -1, -1, -1],
       ...,
       [-1,  1, -1, ..., -1, -1, -1],
       [ 1, -1, -1, ..., -1, -1, -1],
       [-1,  1, -1, ..., -1, -1, -1]])

Now we have a matrix with all labeling functions applied. This matrix has the shape $(instances \times labeling functions)$

In [37]:
print("Shape of applied labeling functions: ", applied_lfs.shape)
print("Number of reviews", len(imdb_dataset_raw))
print("Number of labeling functions", len(labeling_functions))

Shape of applied labeling functions:  (50000, 29)
Number of reviews 50000
Number of labeling functions 29


### Analysis

Now we can analyse some basic stats about our labeling functions. The main figures are:

- Coverage: How many labeling functions match at all
- Overlaps: How many labeling functions overlap with each other (e.g. awesome and amazing)
- Conflicts: How many labeling functions overlap and have different labels (e.g. awesome and bad)
- Correct: Correct LFs
- Incorrect: Incorrect Lfs

In [38]:
LFAnalysis(L=applied_lfs, lfs=labeling_functions).lf_summary()

j Polarity  Coverage  Overlaps  Conflicts
keyword_like         0   [1]      0.51858   0.49426   0.29586  
keyword_good         1   [1]      0.38944   0.37670   0.22624  
keyword_great        2   [1]      0.27614   0.26600   0.12862  
keyword_love         3   [1]      0.25364   0.24712   0.11644  
keyword_best         4   [1]      0.19712   0.19100   0.09734  
keyword_funny        5   [1]      0.13242   0.13242   0.07612  
keyword_excellent    6   [1]      0.07250   0.06944   0.02780  
keyword_fun          7   [1]      0.23214   0.22890   0.12876  
keyword_beautiful    8   [1]      0.08422   0.08150   0.03512  
keyword_interesting  9   [1]      0.11144   0.10734   0.06326  
keyword_wonderful    10  [1]      0.06498   0.06296   0.02336  
keyword_original     11  [1]      0.10622   0.10346   0.06248  
keyword_perfect      12  [1]      0.07940   0.07790   0.03502  
keyword_classic      13  [1]      0.07310   0.07134   0.03650  
keyword_loved        14  [1]      0.05698   0.05698   0.02286  
keyword_recommend    15  [1]      0.08912   0.08606   0.04212  
keyword_amazing      16  [1]      0.04958   0.04808   0.02112  
keyword_favorite     17  [1]      0.04884   0.04788   0.02066  
keyword_bad          18  [0]      0.25408   0.24728   0.23656  
keyword_worst        19  [0]      0.08868   0.08670   0.07932  
keyword_horror       20  [0]      0.08802   0.08640   0.08338  
keyword_awful        21  [0]      0.06238   0.06126   0.05702  
keyword_poor         22  [0]      0.08794   0.08526   0.08044  
keyword_boring       23  [0]      0.06232   0.06066   0.05834  
keyword_stupid       24  [0]      0.06298   0.06164   0.05832  
keyword_terrible     25  [0]      0.05414   0.05296   0.04948  
keyword_waste        26  [0]      0.07312   0.07094   0.06570  
keyword_worse        27  [0]      0.05200   0.05112   0.04736  
keyword_horrible     28  [0]      0.04210   0.04136   0.03854

In [39]:
lf_analysis = LFAnalysis(L=applied_lfs, lfs=labeling_functions).lf_summary()

In [40]:
pd.DataFrame(lf_analysis.mean())

0
j          14.000000
Coverage   0.129780 
Overlaps   0.126032 
Conflicts  0.079798

Lets have a look at some basic examples

In [41]:
imdb_dataset_raw.iloc[applied_lfs[:, 1] == POSITIVE, :].sample(10, random_state=1).loc[:, ['review','sentiment']]

review  \
14708  Some of the greatest and most loved horror movies have a wicked sense of humour, but when a film comes along that isn't as original as the "classics" but just goes at it for laughs then a bunch of po-faced, wanna-be critics completely slag it off. This film made me laugh aloud several times, this is testament to the way this film was approached and it shows. The two main leads look natural and believable together and this really helps this film. You root for them the whole way and laugh along with them, everyone has friends like both of these guys. Another highlight for me was the monster truck, it's awesome, intimidating and really well shot. Taking inspiration (completely stealing) from loads of films, the most obvious being Duel, Jeepers Creepers and probably in reference to the Jack Black alike co-star Orange County. But really you can pick any road trip gone wrong movie and find a reference here. But so what, it's not trying to win any Oscars just give the viewer a good dose of frights and laughs and on that score it's a 10! Obviously It's not getting a 10, I give real sensible reviews and scores unlike 99% of the people on IMDb. There is no-way this movie can get a zero like so many lazy idiots give to too many films and as fun as it was it ain't getting a 10 either. It's just a good fun movie for anyone with a sense of humour and a liking for scares. You really can't get anymore simple than that.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
24770  Maximum risk is quite surprising to a person that has seen more then on of his movies. Director Ringo Lam made an average action-movie, that can be compared with most of the other mid-quality action movies, what is a special predicate to a `Muscles from Brussels`movie. It has a quite classy style, an interesting atmosphere and, last but not least, the beautyful Natasha Henstridge. Even VanDamme doesn´t make you crying by his acting, he does a relatively good job. Of course you may not compare Maximum Risk (oh, what a creative title!) to `Ronin`, but after watching `Knock off` it´s the hell of a good movie... in special standards, of course.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
38047  The way this story played out and the interaction between the 2 lead characters may lead me to believe that if the X-File

## Transform rule matches

To work with knodle the dataset needs to be transformed into a binary array.

0 -> Rule match
1 -> Rule didn't match 

Furthermore, we need a matrix `mapping_rule_labels`

In [42]:
def transform_snorkel_to_knodle(applied_lfs: np.ndarray):
    # All labels other to -1 map to one
    applied_lfs = np.where(applied_lfs!=-1, 1, applied_lfs) 
    
    applied_lfs = np.where(applied_lfs==-1, 0, applied_lfs) 
    
    np.testing.assert_array_equal(np.unique(applied_lfs), np.array([0,1]))
    
    return applied_lfs



In [43]:
applied_lfs = transform_snorkel_to_knodle(applied_lfs)

In [44]:
def create_mapping_rules_labels(keyword_labels: pd.Series) -> np.ndarray:
    """
    This function converts a series of labels ([0,1,1]) into a one-hot enoded vector. 
    This can server as the matrix mapping_rules_labels for knodle. 
    The index is the rule_match and the horizontal axis is tha label id. 
    """
    return pd.get_dummies(keyword_labels, prefix='label').to_numpy()

In [45]:
mapping_rules_labels = create_mapping_rules_labels(keywords.label_id)

In [48]:
rule_label_counts = np.matmul(applied_lfs, mapping_rules_labels)

In [67]:
rule_label_counts.argmax(axis=1)

array([1, 1, 1, ..., 1, 1, 1])

In [54]:
rule_label_counts == rule_label_counts.max()

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [False, False],
       [False, False]])

In [64]:
np.random.random(rule_label_counts.shape)

array([[0.37767603, 0.20029572],
       [0.15193639, 0.20185512],
       [0.20261768, 0.08114917],
       ...,
       [0.90952832, 0.27797398],
       [0.5404479 , 0.59451444],
       [0.44075086, 0.04556974]])

In [66]:
# Indices wo values gleich max
rule_label_counts==rule_label_counts.max()

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [False, False],
       [False, False]])

In [63]:
np.argmax(np.random.random(rule_label_counts.shape) * (rule_label_counts==rule_label_counts.max()), axis=1)

array([0, 0, 0, ..., 0, 0, 0])

In [57]:
np.random.choice(np.flatnonzero(rule_label_counts == rule_label_counts.max()))

77633

In [74]:
c=[np.random.choice(np.flatnonzero(b == b.max())) for i in range(100000)]
np.bincount(c)


array([    0, 32992,     0, 33250,     0, 33758])

In [97]:
np.unique(get_argmax_random_tie(rule_label_counts),return_counts=True)

(array([0, 1]), array([49997,     3]))

In [104]:
# Keine gematchten lfs 
rule_label_counts[np.sum(rule_label_counts, axis=1) == 0].shape


(1883, 2)

In [132]:
rule_matches = transform_snorkel_to_knodle(applied_lfs)
mapping = create_mapping_rules_labels(keywords.label_id)
rule_counts = np.matmul(rule_matches, mapping)

In [133]:
rule_counts

array([[0, 1],
       [0, 2],
       [0, 4],
       ...,
       [1, 2],
       [0, 1],
       [1, 2]])

In [129]:
rule_matches.shape

(50000, 29)

In [126]:
applied_lfs.shape

(50000, 29)

In [124]:
counts = np.argmax(applied_lfs,axis=1)

In [125]:
counts

array([13,  2,  2, ...,  1,  0,  1])

In [112]:
np.where(counts == max(counts), 1, 0)

array([0, 0, 0, ..., 0, 0, 0])

In [114]:
L = applied_lfs

In [137]:
Y_p = np.zeros((n, 2))

In [139]:
Y_p.shape

(50000, 2)

In [140]:
Y_p[0,:].shape

(2,)

In [135]:
np.where(counts == max(counts), 1, 0).shape

(50000,)

In [142]:
counts

array([1., 2.])

In [143]:
n, m = L.shape
Y_p = np.zeros((n, 2))
for i in range(n):
    counts = np.zeros(2)
    for j in range(m):
        if L[i, j] != -1:
            counts[L[i, j]] += 1
    Y_p[i, :] = np.where(counts == max(counts), 1, 0)
# Y_p /= Y_p.sum(axis=1).reshape(-1, 1)

In [144]:
Y_p

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [152]:
rule_counts

array([[0, 1],
       [0, 2],
       [0, 4],
       ...,
       [1, 2],
       [0, 1],
       [1, 2]])

In [155]:
# Rule counts per row
np.max(rule_counts, axis=1)

array([1, 2, 4, ..., 2, 1, 2])

In [158]:
np.where(rule_counts == max(counts), 1, 0)

array([[0, 0],
       [0, 1],
       [0, 0],
       ...,
       [0, 1],
       [0, 0],
       [0, 1]])

In [162]:
rule_counts.sum(axis=1).shape

(50000,)

In [170]:
rule_counts = np.matmul(rule_matches, mapping_rules_labels)

In [180]:
np.isfinite(rule_counts).all()

True

In [174]:
rule_counts / rule_counts.sum(axis=1).reshape(-1,1)

/Users/sandro/.pyenv/versions/3.7.1/envs/imdbTut/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.        , 1.        ],
       [0.        , 1.        ],
       [0.        , 1.        ],
       ...,
       [0.33333333, 0.66666667],
       [0.        , 1.        ],
       [0.33333333, 0.66666667]])

In [ ]:
np.divide(a, b, out=np.zeros_like(a), where=b!=0)

In [185]:
a = rule_counts
b = a.sum(axis=1).reshape(-1,1)
np.divide(a, b, out=np.zeros_like(a), where=b!=0)

TypeError: No loop matching the specified signature and casting was found for ufunc true_divide

In [190]:
probs = rule_counts / rule_counts.sum(axis=1).reshape(-1,1)

/Users/sandro/.pyenv/versions/3.7.1/envs/imdbTut/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [192]:
probs[np.isnan(probs)] = 0

In [193]:
np.unique(probs, return_counts=True)

(array([0.        , 0.06666667, 0.07142857, 0.07692308, 0.08333333,
        0.09090909, 0.1       , 0.11111111, 0.125     , 0.14285714,
        0.15384615, 0.16666667, 0.18181818, 0.2       , 0.21428571,
        0.22222222, 0.23076923, 0.25      , 0.26666667, 0.27272727,
        0.28571429, 0.3       , 0.30769231, 0.3125    , 0.33333333,
        0.35714286, 0.36363636, 0.375     , 0.38461538, 0.4       ,
        0.41666667, 0.42857143, 0.4375    , 0.44444444, 0.45454545,
        0.46153846, 0.46666667, 0.5       , 0.53333333, 0.53846154,
        0.54545455, 0.55555556, 0.5625    , 0.57142857, 0.58333333,
        0.6       , 0.61538462, 0.625     , 0.63636364, 0.64285714,
        0.66666667, 0.6875    , 0.69230769, 0.7       , 0.71428571,
        0.72727273, 0.73333333, 0.75      , 0.76923077, 0.77777778,
        0.78571429, 0.8       , 0.81818182, 0.83333333, 0.84615385,
        0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
        0.91666667, 0.92307692, 0.92857143, 0.93

array([0, 1])

### Majority Vote

Now we make a majority vote based on all rule matches.

In [194]:
def get_majority_vote_probs(rule_matches: np.ndarray, mapping_rules_labels: np.ndarray): 
    rule_counts = np.matmul(rule_matches, mapping_rules_labels)
    rule_counts_probs = rule_counts / rule_counts.sum(axis=1).reshape(-1,1)
    
    # Set probability zero if it was devided with zero
    rule_counts_probs[np.isnan(rule_counts_probs)] = 0
    return rule_counts_probs

In [195]:
y_probs = get_majority_vote_probs(rule_matches, mapping_rules_labels)

/Users/sandro/.pyenv/versions/3.7.1/envs/imdbTut/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [196]:
# Positive is a bit overrepresented
np.unique(y_probs, return_counts=True)

(array([0.        , 0.06666667, 0.07142857, 0.07692308, 0.08333333,
        0.09090909, 0.1       , 0.11111111, 0.125     , 0.14285714,
        0.15384615, 0.16666667, 0.18181818, 0.2       , 0.21428571,
        0.22222222, 0.23076923, 0.25      , 0.26666667, 0.27272727,
        0.28571429, 0.3       , 0.30769231, 0.3125    , 0.33333333,
        0.35714286, 0.36363636, 0.375     , 0.38461538, 0.4       ,
        0.41666667, 0.42857143, 0.4375    , 0.44444444, 0.45454545,
        0.46153846, 0.46666667, 0.5       , 0.53333333, 0.53846154,
        0.54545455, 0.55555556, 0.5625    , 0.57142857, 0.58333333,
        0.6       , 0.61538462, 0.625     , 0.63636364, 0.64285714,
        0.66666667, 0.6875    , 0.69230769, 0.7       , 0.71428571,
        0.72727273, 0.73333333, 0.75      , 0.76923077, 0.77777778,
        0.78571429, 0.8       , 0.81818182, 0.83333333, 0.84615385,
        0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
        0.91666667, 0.92307692, 0.92857143, 0.93

In [198]:
y_probs.shape

(50000, 2)

In [ ]:
imdb_dataset_raw['label_id'] = imdb_dataset_raw.sentiment.map({'positive':POSITIVE, 'negative':NEGATIVE})

In [ ]:
imdb_dataset_raw['prediction'] = predictions

In [ ]:
acc = np.sum(imdb_dataset_raw.label_id == imdb_dataset_raw.prediction) / len(imdb_dataset_raw)
print("Accuracy of Majority Vote model is: ", acc)

## Save Files


In [ ]:
from joblib import dump

In [ ]:
dump(applied_lfs, 'applied_lfs.lib')


In [ ]:
keywords.to_csv('keywords.csv', index=None)


In [ ]:
imdb_dataset_raw.to_csv('imdb_data_preprocessed.csv', index=None)

# Finish

Now, we have created a weak supervision dataset. Of course it is not perfect but it is something with which we can compare performances of different denoising methods with. :-) 